# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AR in Retails' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#
#pod 'GoogleMaps'
#pod ‘EstimoteIndoorSDK’
#pod 'EstimoteProximitySDK'
#pod 'ApiAI'
#pod 'IQKeyboardManagerSwift'
#pod 'JSQMessagesViewController'
end
