# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  

  # install cocoapods freshly
  def install_pods
    cocoapods(
      clean: true,
      podfile: "Podfile",
      try_repo_update_on_error: true
    )
  end

  lane :beta do
  	puts("this is my first 🚀 lane")
  	install_pods()
  	#increment_build_number(build_number: latest_testflight_build_number + 1,xcodeproj: "AR in Retails.xcodeproj")
    build_app(workspace: "AR in Retails.xcworkspace", scheme: "AR in Retails")
    upload_to_testflight
    slack(message: "Successfully distributed a new beta build", slack_url: "https://walmart.slack.com/messages/CAQS2PL1X/details/")
  end

  desc "Create ipa"
  lane :build do
  	install_pods()
    gym
  end
end
